title: aktas
description: "aktas'ın mekanı"
author:
  name: "aktas"
  email: "aktsalper@protonmail.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "aktas"
year : "2022"
google_analytics: "G-07K93SGEQM"
